Update required weasyprint to 63
WeasyPrint 62.3 and earlier versions specify pydyf >=0.10.0 with no
upper bound. pydyf 0.11.0+ has a breaking API change that which results
in a failure building PDFs:

    AttributeError: 'super' object has no attribute 'transform'

Support for newer versions of pydyf was introduced in weasyprint 63.